
# Python 3.10
FROM python:3.10-slim-buster

RUN apt-get update && apt-get install -y \
        zip \
        && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade --ignore-installed setuptools six pip \
    && pip install --upgrade --no-cache-dir --ignore-installed \
        boto3 \
        pika \
        glob2 \
        redis \
        requests \
        PyYAML \
        kubernetes \
        numpy \
        cloudpickle \
        ps-mem \
        tblib \
        matplotlib \
        psutil

# Copy Lithops proxy and lib to the container image.
ENV APP_HOME /lithops
WORKDIR $APP_HOME

COPY lithops_aws_batch.zip .
RUN unzip lithops_aws_batch.zip && rm lithops_aws_batch.zip

COPY tensei.zip ${FUNCTION_DIR}
RUN mkdir tensei-dir \
    && mv tensei.zip tensei-dir \
    && cd tensei-dir \
    && unzip tensei.zip \
    && pip3 install -e . \
    && cd ..

ENTRYPOINT python entry_point.py